export const EVENTS = {
  INPUT_EVENT: 'input-event',
  INPUT_LISTENER_ERROR: 'input-listener-error',
  MERIT_UPDATED: 'merit-updated',
  SETTINGS_UPDATED: 'settings-updated',
  WOODEN_FISH_SKINS_UPDATED: 'wooden-fish-skins-updated',
} as const

export const COMMANDS = {
  ADD_MERIT: 'add_merit',
  CHECK_UPDATE: 'check_update',
  DOWNLOAD_AND_INSTALL_UPDATE: 'download_and_install_update',
  START_INPUT_LISTENING: 'start_input_listening',
  STOP_INPUT_LISTENING: 'stop_input_listening',
  TOGGLE_INPUT_LISTENING: 'toggle_input_listening',
  IS_INPUT_LISTENING: 'is_input_listening',
  GET_INPUT_LISTENER_ERROR: 'get_input_listener_error',
  CHECK_INPUT_MONITORING_PERMISSION: 'check_input_monitoring_permission',
  REQUEST_INPUT_MONITORING_PERMISSION: 'request_input_monitoring_permission',
  OPEN_INPUT_MONITORING_SETTINGS: 'open_input_monitoring_settings',
  UPDATE_INPUT_SETTINGS: 'update_input_settings',
  GET_MERIT_STATS: 'get_merit_stats',
  GET_RECENT_DAYS: 'get_recent_days',
  CLEAR_HISTORY: 'clear_history',
  RESET_ALL_MERIT: 'reset_all_merit',
  GET_SETTINGS: 'get_settings',
  UPDATE_SETTINGS: 'update_settings',
  TOGGLE_WINDOW_PASS_THROUGH: 'toggle_window_pass_through',
  TOGGLE_ALWAYS_ON_TOP: 'toggle_always_on_top',
  SHOW_MAIN_WINDOW: 'show_main_window',
  HIDE_MAIN_WINDOW: 'hide_main_window',
  TOGGLE_MAIN_WINDOW: 'toggle_main_window',
  SHOW_SETTINGS_WINDOW: 'show_settings_window',
  HIDE_SETTINGS_WINDOW: 'hide_settings_window',
  TOGGLE_SETTINGS_WINDOW: 'toggle_settings_window',
  QUIT_APP: 'quit_app',
  AUTOSTART_IS_ENABLED: 'autostart_is_enabled',
  AUTOSTART_ENABLE: 'autostart_enable',
  AUTOSTART_DISABLE: 'autostart_disable',
  GET_CUSTOM_WOODEN_FISH_SKINS: 'get_custom_wooden_fish_skins',
  IMPORT_CUSTOM_WOODEN_FISH_SKIN_ZIP: 'import_custom_wooden_fish_skin_zip',
  DELETE_CUSTOM_WOODEN_FISH_SKIN: 'delete_custom_wooden_fish_skin',
  EXPORT_WOODEN_FISH_SKIN_ZIP: 'export_wooden_fish_skin_zip',
} as const
